// <auto-generated />
using System;
using ListaParaFazer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ListaParaFazer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240523143804_alteração em alguns campos")]
    partial class alteraçãoemalgunscampos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.17");

            modelBuilder.Entity("ListaParaFazer.Models.Entities.TarefaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataFinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("SMALLDATETIME")
                        .HasDefaultValue(new DateTime(2024, 5, 24, 14, 38, 4, 618, DateTimeKind.Utc).AddTicks(4755))
                        .HasColumnName("DataFinal");

                    b.Property<DateTime?>("DataInicial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("SMALLDATETIME")
                        .HasDefaultValue(new DateTime(2024, 5, 23, 14, 38, 4, 618, DateTimeKind.Utc).AddTicks(4494))
                        .HasColumnName("DataInicial");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Descricao");

                    b.Property<int?>("DiasParaRealizar")
                        .HasColumnType("int")
                        .HasColumnName("DiasParaRealizar");

                    b.Property<bool?>("Realizada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false)
                        .HasColumnName("Realizada");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.ToTable("TB_Tarefas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
