// <auto-generated />
using System;
using ListaParaFazer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ListaParaFazer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240522120436_Configuranto Mapeamento")]
    partial class ConfigurantoMapeamento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.17");

            modelBuilder.Entity("ListaParaFazer.Models.TarefaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataFinal")
                        .HasColumnType("SMALLDATETIME")
                        .HasColumnName("DataFinal");

                    b.Property<DateTime?>("DataInicial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("SMALLDATETIME")
                        .HasDefaultValue(new DateTime(2024, 5, 22, 12, 4, 36, 310, DateTimeKind.Utc).AddTicks(2533))
                        .HasColumnName("DataInicial");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Descricao");

                    b.Property<int?>("DiasParaRealizar")
                        .HasColumnType("int")
                        .HasColumnName("DiasParaRealizar");

                    b.Property<bool?>("Realizada")
                        .IsRequired()
                        .HasColumnType("BIT")
                        .HasColumnName("Realizada");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.ToTable("TB_Tarefas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
